"""initial schema

Revision ID: b26a74944e68
Revises: 
Create Date: 2026-08-02 11:34:40.108257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26a74944e68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tower_records',
    sa.Column('tower_id', sa.Uuid(), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('radio', sa.String(length=50), nullable=False),
    sa.Column('mcc', sa.Integer(), nullable=False),
    sa.Column('mnc', sa.Integer(), nullable=False),
    sa.Column('lac', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('cgi', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('azimuth', sa.Float(), nullable=True),
    sa.Column('beamwidth', sa.Float(), nullable=True),
    sa.Column('range_meters', sa.Float(), nullable=True),
    sa.Column('site_address', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('tower_id')
    )
    op.create_index(op.f('ix_tower_records_cgi'), 'tower_records', ['cgi'], unique=True)
    op.create_table('upload_metadata',
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_index(op.f('ix_upload_metadata_case_id'), 'upload_metadata', ['case_id'], unique=False)
    op.create_index(op.f('ix_upload_metadata_sha256'), 'upload_metadata', ['sha256'], unique=True)
    op.create_table('measurement_frames',
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('subscriber_identifier', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_metadata.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('frame_id')
    )
    op.create_index(op.f('ix_measurement_frames_subscriber_identifier'), 'measurement_frames', ['subscriber_identifier'], unique=False)
    op.create_index(op.f('ix_measurement_frames_timestamp'), 'measurement_frames', ['timestamp'], unique=False)
    op.create_index(op.f('ix_measurement_frames_upload_id'), 'measurement_frames', ['upload_id'], unique=False)
    op.create_table('subscriber_event_records',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('imei', sa.String(length=50), nullable=True),
    sa.Column('imsi', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('call_type', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('cgi', sa.String(length=100), nullable=False),
    sa.Column('mcc', sa.Integer(), nullable=True),
    sa.Column('mnc', sa.Integer(), nullable=True),
    sa.Column('lac', sa.Integer(), nullable=True),
    sa.Column('cell_id', sa.Integer(), nullable=True),
    sa.Column('tower_latitude', sa.Float(), nullable=True),
    sa.Column('tower_longitude', sa.Float(), nullable=True),
    sa.Column('signal_strength', sa.Float(), nullable=True),
    sa.Column('timing_advance', sa.Integer(), nullable=True),
    sa.Column('rtt', sa.Float(), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('record_number', sa.Integer(), nullable=False),
    sa.Column('raw_fields', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_metadata.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_subscriber_event_records_cgi'), 'subscriber_event_records', ['cgi'], unique=False)
    op.create_index(op.f('ix_subscriber_event_records_imei'), 'subscriber_event_records', ['imei'], unique=False)
    op.create_index(op.f('ix_subscriber_event_records_imsi'), 'subscriber_event_records', ['imsi'], unique=False)
    op.create_index(op.f('ix_subscriber_event_records_phone_number'), 'subscriber_event_records', ['phone_number'], unique=False)
    op.create_index(op.f('ix_subscriber_event_records_timestamp'), 'subscriber_event_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_subscriber_event_records_upload_id'), 'subscriber_event_records', ['upload_id'], unique=False)
    op.create_table('measurement_towers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('tower_id', sa.Uuid(), nullable=False),
    sa.Column('cgi', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('azimuth', sa.Float(), nullable=True),
    sa.Column('beamwidth', sa.Float(), nullable=True),
    sa.Column('signal_strength', sa.Float(), nullable=True),
    sa.Column('timing_advance', sa.Integer(), nullable=True),
    sa.Column('rtt', sa.Float(), nullable=True),
    sa.Column('pseudorange_meters', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['measurement_frames.frame_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tower_id'], ['tower_records.tower_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_towers_frame_id'), 'measurement_towers', ['frame_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurement_towers_frame_id'), table_name='measurement_towers')
    op.drop_table('measurement_towers')
    op.drop_index(op.f('ix_subscriber_event_records_upload_id'), table_name='subscriber_event_records')
    op.drop_index(op.f('ix_subscriber_event_records_timestamp'), table_name='subscriber_event_records')
    op.drop_index(op.f('ix_subscriber_event_records_phone_number'), table_name='subscriber_event_records')
    op.drop_index(op.f('ix_subscriber_event_records_imsi'), table_name='subscriber_event_records')
    op.drop_index(op.f('ix_subscriber_event_records_imei'), table_name='subscriber_event_records')
    op.drop_index(op.f('ix_subscriber_event_records_cgi'), table_name='subscriber_event_records')
    op.drop_table('subscriber_event_records')
    op.drop_index(op.f('ix_measurement_frames_upload_id'), table_name='measurement_frames')
    op.drop_index(op.f('ix_measurement_frames_timestamp'), table_name='measurement_frames')
    op.drop_index(op.f('ix_measurement_frames_subscriber_identifier'), table_name='measurement_frames')
    op.drop_table('measurement_frames')
    op.drop_index(op.f('ix_upload_metadata_sha256'), table_name='upload_metadata')
    op.drop_index(op.f('ix_upload_metadata_case_id'), table_name='upload_metadata')
    op.drop_table('upload_metadata')
    op.drop_index(op.f('ix_tower_records_cgi'), table_name='tower_records')
    op.drop_table('tower_records')
    # ### end Alembic commands ###
