"""
Unit tests for AirtelExtractor.
Verifies parsing of standard files, skipping of malformed rows, preambles, and missing columns.
"""

from typing import Any
from uuid import uuid4
import pytest

from app.contracts.enums import CallType, Operator, SourceType
from app.ingestion.extractors.airtel import AirtelExtractor


@pytest.fixture
def extractor() -> AirtelExtractor:
    """
    Instance fixture for AirtelExtractor.
    """
    return AirtelExtractor()


def test_airtel_extractor_valid_csv(tmp_path: Any, extractor: AirtelExtractor) -> None:
    """
    Tests parsing a standard Airtel CDR CSV containing headers and data.
    """
    file_path = tmp_path / "airtel_valid.csv"
    content = (
        "calling_no,called_no,first_cgi,imei,imsi,datetime,duration,type,lac,cell_id,first cgi lat/long\n"
        "919876543210,919876543211,404-45-1234-5678,358765432109876,404450123456789,2026-07-29 10:00:00,120,MOC,1234,5678,28.6139/77.2090\n"
        "919876543210,919876543212,404-45-1234-5678,358765432109876,404450123456789,2026-07-29 10:05:00,45,MTC,1234,5678,28.6139/77.2090\n"
    )
    file_path.write_text(content)

    upload_id = uuid4()
    records = extractor.extract(str(file_path), upload_id)
    assert len(records) == 2

    r1 = records[0]
    assert r1.operator == Operator.AIRTEL
    assert r1.upload_id == upload_id
    assert r1.source_type == SourceType.CDR
    assert r1.phone_number == "919876543210"
    assert r1.imei == "358765432109876"
    assert r1.imsi == "404450123456789"
    assert r1.cgi == "404-45-1234-5678"
    assert r1.duration_seconds == 120
    assert r1.call_type == CallType.OUTGOING
    assert r1.lac == 1234
    assert r1.cell_id == 5678
    assert r1.tower_latitude == 28.6139
    assert r1.tower_longitude == 77.2090
    assert r1.record_number == 1


def test_airtel_extractor_missing_optional_columns(tmp_path: Any, extractor: AirtelExtractor) -> None:
    """
    Checks that the extractor functions when optional fields (lac, cell_id, coords) are missing.
    """
    file_path = tmp_path / "airtel_missing_opts.csv"
    # Only provides mandatory identifiers, CGI, timestamp, and duration
    content = (
        "calling_no,first_cgi,datetime\n"
        "919876543210,404-45-0-0,2026-07-29 10:15:00\n"
    )
    file_path.write_text(content)

    upload_id = uuid4()
    records = extractor.extract(str(file_path), upload_id)
    assert len(records) == 1

    r = records[0]
    assert r.upload_id == upload_id
    assert r.phone_number == "919876543210"
    assert r.cgi == "404-45-0-0"
    assert r.imei is None
    assert r.lac is None
    assert r.tower_latitude is None
    assert r.duration_seconds == 0  # defaults to 0


def test_airtel_extractor_malformed_rows(tmp_path: Any, extractor: AirtelExtractor) -> None:
    """
    Verifies malformed rows are skipped (logged) without interrupting the complete run.
    """
    file_path = tmp_path / "airtel_malformed.csv"
    content = (
        "calling_no,first_cgi,datetime\n"
        "919876543210,404-45-1234-5678,2026-07-29 10:00:00\n"  # Valid
        "919876543210,,2026-07-29 10:05:00\n"                  # Malformed (missing CGI)
        "919876543210,404-45-1234-5678,invalid_datetime\n"     # Malformed (bad date)
        "919876543210,404-45-1234-5678,2026-07-29 10:10:00\n"  # Valid
    )
    file_path.write_text(content)

    upload_id = uuid4()
    records = extractor.extract(str(file_path), upload_id)
    assert len(records) == 2  # Only row 1 and row 4 are valid
    assert records[0].upload_id == upload_id
    assert records[1].upload_id == upload_id
    assert records[0].record_number == 1
    assert records[1].record_number == 4


def test_airtel_extractor_metadata_preamble(tmp_path: Any, extractor: AirtelExtractor) -> None:
    """
    Asserts headers density scanning correctly ignores file metadata comments at the top.
    """
    file_path = tmp_path / "airtel_preamble.csv"
    content = (
        "Investigation Title: Suspect Phone Ingress Map\n"
        "Generated By: TeleCom ISP Server\n"
        "Target Cell Circle: Delhi NCR\n"
        "\n"
        "calling_no,first_cgi,datetime\n"
        "919876543210,404-45-1234-5678,2026-07-29 10:00:00\n"
    )
    file_path.write_text(content)

    upload_id = uuid4()
    records = extractor.extract(str(file_path), upload_id)
    assert len(records) == 1
    assert records[0].upload_id == upload_id
    assert records[0].phone_number == "919876543210"
    assert records[0].cgi == "404-45-1234-5678"


def test_airtel_extractor_empty_file(tmp_path: Any, extractor: AirtelExtractor) -> None:
    """
    Asserts empty files return an empty list of records.
    """
    file_path = tmp_path / "airtel_empty.csv"
    file_path.write_text("")

    upload_id = uuid4()
    records = extractor.extract(str(file_path), upload_id)
    assert records == []
